#!/usr/bin/env bash

source /app/helper.sh

function create_ext {
    local host="${1:?}"

    cat << EOF > "$CERT_PATH/$host.ext"
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
subjectAltName = @alt_names
[alt_names]
DNS.1 = $host
EOF
}

function expired_cert {
    local crt="${1:?}"

    ! openssl x509 -checkend 0 -noout -in "$crt" >/dev/null 2>&1
}

function generate_cert {
    local host="${1:?}"
    local crt="$CERT_PATH/$host.crt"
    local key="$CERT_PATH/$host.key"
    local csr="$CERT_PATH/$host.csr"
    local ext="$CERT_PATH/$host.ext"
    local srl="$CERT_PATH/$host.srl"

    create_ext "$host"

    echo "Generating self-signed certificate for $host..."

    if ! openssl req \
        -new \
        -sha256 \
        -nodes \
        -newkey rsa:2048 \
        -subj "/CN=$host" \
        -keyout "$key" \
        -out "$csr";
    then
        echo "Failed to generate certificate request for $host."
        return 1
    fi

    if ! openssl x509 \
        -req \
        -in "$csr" \
        -sha256 \
        -days "$SELFSIGNED_EXPIRY" \
        -CA "$CERT_PATH/ca/ca.crt" \
        -CAkey "$CERT_PATH/ca/ca.key" \
        -CAcreateserial \
        -extfile "$ext" \
        -out "$crt";
    then
        echo "Failed to sign certificate for $host."
        return 1
    fi

    rm -f "$ext" "$csr" "$srl"
}

function cleanup_cert {
    local host="${1:?}"

    local crt="$CERT_PATH/$host.crt"
    local key="$CERT_PATH/$host.key"

    echo "Cleaning up certificate for $host."
    rm -f "$crt" "$key"
}

function process_cert {
    local cid="${1:?}"
    local -n hosts="SELFSIGNED_${cid}_HOSTS"

    for host in "${hosts[@]}"; do
        local crt="$CERT_PATH/$host.crt"
        local key="$CERT_PATH/$host.key"

        if [[ ! -f "$crt" || ! -f "$key" ]] || expired_cert "$crt"; then
            [[ -f "$crt" ]] && echo "Certificate for $host has expired and will be regenerated."
            generate_cert "$host"
        fi
    done
}

function cleanup_certs {
    local existing_hosts=()

    for cid in "${SELFSIGNED_CONTAINERS[@]}"; do
        local -n hosts="SELFSIGNED_${cid}_HOSTS"

        for host in "${hosts[@]}"; do
            existing_hosts+=("$host")
        done
    done

    shopt -s nullglob

    for path in "$CERT_PATH"/*.crt; do
        local host="${path##*/}"
        host="${host%.crt}"

        if [[ ! " ${existing_hosts[*]} " =~ " ${host} " ]] && expired_cert "$path"; then
            cleanup_cert "$host"
        fi
    done

    shopt -u nullglob
}

function process_certs {
    if [[ -f /tmp/selfsigned_service_data ]]; then
        # shellcheck disable=SC1091
        source /tmp/selfsigned_service_data
    else
        echo "Warning: /tmp/selfsigned_service_data not found, skipping data from containers."
    fi

    local should_reload_nginx='false'

    for cid in "${SELFSIGNED_CONTAINERS[@]}"; do
        process_cert "$cid"
    done

    cleanup_certs && should_reload_nginx='true'

    [[ "$should_reload_nginx" == 'true' ]] && reload_nginx

    reload_nginx
}

process_certs "$@"
